# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/jobs-steps/#jobs-overview & https://circleci.com/docs/configuration-reference/#jobs
jobs:
  build-and-test:
    # Specify the execution environment with Python 3.9
    docker:
      - image: cimg/python:3.9

    # Add steps to the job
    steps:
      # Checkout the code as the first step
      - checkout
      
      # Install system dependencies
      - run:
          name: Install system dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y liblapack-dev libblas-dev gfortran
      
      # Set up Python environment
      - run:
          name: Install dependencies
          command: |
            python -m pip install --upgrade pip
            python -m pip install pytest numpy autograd scipy
            # Install the project
            pip install .
      
      # Run tests
      - run:
          name: Run tests
          command: |
            pytest examples/

# Orchestrate jobs using workflows
# See: https://circleci.com/docs/workflows/ & https://circleci.com/docs/configuration-reference/#workflows
workflows:
  test-workflow:
    jobs:
      - build-and-test